#! /bin/sh

# Get colors
focusColor=$(xrdb -query -all | grep '*.highlightColor:' | sed "s/\*.highlightColor:\t//")
foreground=$(xrdb -query -all | grep '*.foreground:' | sed "s/\*.foreground:\t//")

# Kill all running applications before starting
killall -9 sxhkd lemonbar

sxhkd &
~/.config/bar/lemonbar.sh &

xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            8

bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config normal_border_color   ${foreground}
bspc config focused_border_color  ${focusColor}

bspc config bottom_padding        10
bspc config top_padding           10
bspc config left_padding          10
bspc config right_padding         10

feh --bg-fill ~/share/wallpaper.jpg

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
